#spring:
#  config:
#    activate:
#      on-profile: local
#  logging:
#    config: classpath:logconfig/logback-spring.xml
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  logging:
#    config: classpath:logconfig/logback-spring.xml
#
