server:
  port: 7777

spring:
  config:
    activate:
      on-profile: linux
  data:
    jdbc:
      repositories:
        enabled = true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.16.72.131:5432/delivery_db
    username: guscjf0903
    password: tnthtn35
  jpa:
    hibernate:
      ddl-auto: none



logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

