server:
  port: 8888
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    group:
      default: profile1
      mac: profile1
      linux: profile2

---
spring:
  config:
    activate:
      on-profile: profile1


api:
  url: http://localhost:7777
---
spring:
  config:
    activate:
      on-profile: profile2


api:
  url: http://172.16.72.130:7777

